### ISSUE TITLE
Trader blacklist

### ISSUE THREAD

**Issue by Dominik-O22** [exiletrade/exiletrade#70]
i think this would be a nice addition, so the user can easily exclude sellers from their results without the need to specify it in the searchbar

**Comment by thirdy** [comment]
this can be done via search prefix:

 (-accountA OR -ignA OR -ignB)

yeah it's not intuitive; just worth mentioning that, it is possible

On Mon, Mar 28, 2016 at 10:56 PM, Dom notifications@github.com wrote:

> i think this would be a nice addition, so the user can easily exclude
> sellers from their results without the need to specify it in the searchbar
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/exiletrade/exiletrade/issues/70

## 

## 

http://sites.google.com/site/thirdyderivera/

**Comment by Dominik-O22** [comment]
there is no such term as ign or account, what we do have is seller, which matches for both, and yes i know that it can be done that way just would be nice to have the option to add it to the blacklist automatically by just clicking a button instead of writing it down, additionally then we could blacklist the account name and not just the ign,the thing we display

**Comment by thirdy** [comment]
agreed.

having a button on the item will be neat.

should probably be an account blacklist and not ign

On Mon, Apr 4, 2016 at 7:36 AM, Dom notifications@github.com wrote:

> there is no such term as ign or account, what we do have is seller, which
> matches for both, and yes i know that it can be done that way just would be
> nice to have the option to add it to the blacklist automatically by just
> clicking a button instead of writing it down, additionally then we could
> blacklist the account name and not just the ign,the thing we display
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/exiletrade/exiletrade/issues/70#issuecomment-205077423

## 

## 

http://sites.google.com/site/thirdyderivera/

**Comment by Eruyome** [comment]
This would require a function to export and import this blacklist. If you blacklist 100+ people you can't repeat that for every different browser/device you could use. You could also edit the list that way. And some kind of editor to remove people from that list would be nice, too.

**Comment by Eruyome** [comment]
I've implemented the account/player blacklist feature except actually filtering results. At the moment this feature is disabled by setting $scope.enableBlacklistFeature = false;. If enabled you can add a players account with an optional comment and added timestamp to the blacklist. the blacklist is saved to localstorage and can be managed with a modal window found under options. You can export the list to JSON, import the JSON file and remove players from the list. The table displaying the players can be sorted and filtered via text input.

**Comment by kyri0** [comment]
This seems awesome, man. People would be able to share blacklists of known bad users. Really impressive. Gonna test it.

**Comment by thirdy** [comment]
Done, pushed my changes.

Aside from filtering blacklisted items.

I've also added a variables:

{{Response.blacklisted}} - counts how many of the items are in blacklist
{{Response.offline}} - counts how many of the items are offline

@Eruyome , will leave it to you to display these.

Nice work btw; great UI.

**Comment by Eruyome** [comment]
Just to be clear: Do we have a blacklist feature that is actually working or not? Do we still see items of blacklisted users?

> Aside from filtering blacklisted items.

**Comment by thirdy** [comment]
It's working, tested it
